# Generated by Django 3.1.4 on 2020-12-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substitute', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='favorite',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_favorite', to='substitute.User'),
        ),
    ]
